### ISSUE TITLE
error mounting dir on file

### ISSUE THREAD

**Issue by lagan-tsrb** [lebe-dev/mail-utilities-wizard#1]
Hello, after run docker compose up -d, terminal out error:
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/mail-utilities-wizard/config.yml" to rootfs at "/app/config.yml": mount /mail-utilities-wizard/config.yml:/app/config.yml (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.
hello from habr)

**Comment by lebe-dev** [comment]
Hi.

Thanks for feedback.

You should prepare `config.yml` file:

```shell
cp config.yml-dist config.yml

# Edit config.yml

docker-compose up -d
```

I've updated README.md.

**Comment by lagan-tsrb** [comment]
thanks,
or add new error in logs
thread 'main' panicked at src/logging.rs:52:10:
couldn't build rolling appender: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by lebe-dev** [comment]
Are you sure you did `chmod -R 777 logs`? Try again please:

```shell
docker-compose down
mkdir -p logs
chmod 777 logs
docker-compose up -d
```

**Comment by lagan-tsrb** [comment]
thank you,
and new error :( 
in browser: While the page was loading, the connection to the server was reset.
i correct file docker-compose.yml and replace string "-8080:8080" on "-81:8080" port 8080 bused on my host.

**Comment by lebe-dev** [comment]
Please show me the complete `docker-compose.yml`.

**Comment by lagan-tsrb** [comment]
version: '3.3'

services:
  app:
    container_name: mail-utilities-wizard
    image: registry.gitlab.com/tiny-services/mail-utilities-wizard:1.1.0
    restart: always
    volumes:
      - ./config.yml:/app/config.yml
      - ./templates:/app/templates
      - ./logs:/app/logs
    ports:
      - "81:8080"

  # Debug mail
  #mailhog:
  #  container_name: mailhog
  #  image: mailhog/mailhog
  #  restart: always
  #  ports:
  #    - "1025:1025"
  #    - "8025:8025"

**Comment by lebe-dev** [comment]
Try to use port number from non-privileged range (>1000), i. e. 3080.

**Comment by lagan-tsrb** [comment]
but non  port > 1000  not job
error: While the page was loading, the connection to the server was reset.
realese my host port 8080, not job

**Comment by lebe-dev** [comment]
Please change in config.yml:

```
bind: 127.0.0.1:8080
```

to:

```
0.0.0.0:8080
```

then:

```
docker-compose down
docker-compose up -d
```

**Comment by lagan-tsrb** [comment]
add change in file. 
`Error response from daemon: driver failed programming external connectivity on endpoint mail-utilities-wizard (85bf0c6947381309f286a90501bdcd1e2de5ed4b72097a7230f0d563e51343f3): Error starting userland proxy: listen tcp4 0.0.0.0:8080: bind: address already in use`

**Comment by lebe-dev** [comment]
Something is using port. Try a different port in config.yml and docker-compose.yml

**Comment by lagan-tsrb** [comment]
thank you!!! site job in browser )))

**Comment by lebe-dev** [comment]
Awesome. Enjoy :)
